.TH GIT-NETHACK 1
.CT 1 files prog_other
.SH NAME
git-nethack \- Hack while you hack
.SH SYNOPSIS
git nethack
.SH DESCRIPTION
This command loads nethack, the dungeon exploration game.

For more information on nethack, see
.BI http://nethack.org .

.SH OPTIONS

There aren't any.

.SH BUGS
You must have nethack installed in your path to play.

Does not track your save file in the git repo.

.SH SEE ALSO
.IR git-zombocom(1)

.SH GIT
Not yet part of the official
.I git(1)
suite.
